### PR TITLE
[Codebase improvement] Reuse handlers devopsProject to devops

### PR DESCRIPTION
**Pull request by Feeeenng**
reuse  handler devopsProject to devops. and queryParam to query

### CODE REVIEW

**Comment by JohnNiang** [comment]
@Feeeenng , thanks for your first contribution.

/lgtm
/cc @kubesphere/sig-devops

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
Thanks for your contribution. But please see the following warning (which come from Goland)

image

**Comment by JohnNiang** [comment]
> Thanks for your contribution. But please see the following warning (which come from Goland)
> 
> image

IMO,  some people use `VSCode` as their IDE which lint tool is `golangci-lint`, and no warning here due to [.golangci.yaml](https://github.com/kubesphere/ks-devops/blob/master/.golangci.yml) agreed.

If we don't want to see the warning again, please configure lint tools in IDEA.

So I think there is no problem.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
