### PR TITLE
Correct the GitHub org in the README file

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Signed-off-by: rick <LinuxSuRen@users.noreply.github.com>

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
> @JohnNiang: changing LGTM is restricted to collaborators

It's weird. You're one of the reviewers

https://github.com/kubesphere/ks-devops/blob/7714e9c334ad2f2c68bad2260415047eea71b7e2/OWNERS#L4

**Comment by JohnNiang** [comment]
hi @LinuxSuRen , I found that [fossa page](https://app.fossa.com/projects/git%2Bgithub.com%2Fkubesphere%2Fks-devops?ref=badge_large) is not found jsut now. please see the picture below.

image

**Comment by LinuxSuRen** [comment]
Good catch. The KubeSphere org didn't give the access for it.

**Pull request merged**
