### PR TITLE
add tekton chart for installation

### LINKED ISSUE #62: Add Tekton charts into ks-devops
Integrate Tekton into ks-devops by adding chart installation in `charts/ks-devops/charts/`

### PR DESCRIPTION
**Pull request by flamywhale**
resolves #62 

Description:
* Add tekton pipeline chart into ks-devops for installation of tekton. 
* We can use `make install-chart` in command line to install Jenkins, s2i and tekton-pipeline.
* After successfully installing the chart, the tekton components are deployed in the namespace called `tekton-pipelines`.

### CODE REVIEW

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
Thanks for your contribution. But IMO, we don't have a good reason to maintain the Tekton helm chart. So, it's not a good idea to commit the source files of it into this repository. I have two suggestions here:

* commit and commit a specific release helm chart of Tekton
  * it should be a file likes `xxx.tgz`
* create a PR against the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support)
  * we can merge the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support) into master when it's ready

**Comment by flamywhale** [comment]
> Thanks for your contribution. But IMO, we don't have a good reason to maintain the Tekton helm chart. So, it's not a good idea to commit the source files of it into this repository. I have two suggestions here:
> 
> * commit and commit a specific release helm chart of Tekton
>   
>   * it should be a file likes `xxx.tgz`
> * create a PR against the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support)
>   
>   * we can merge the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support) into master when it's ready

Okay, Master. I would like to use the former solution.

**Comment by flamywhale** [comment]
> Thanks for your contribution. But I have a question for you: what should we do if we want to install ks-devops without tekton?

How about adding `condition` field in the parent `Chart.yaml` to controll dependecies and adding `charts.xxx.enabled` in `values.yaml`?
e.g. 
``` yaml
# Chart.yaml
...
dependencies:
  - name: jenkins
    version: 0.19.0
    condition: charts.jenkins.enabled
  - name: s2i
    version: 1.16.0
    condition: charts.s2i.enabled
  - name: tekton-pipeline
    version: 0.25.0
    condition: charts.tekton.enabled
...

# values.yaml
...
charts:
  jenkins:
    enabled: true
  s2i:
    enabled: true
  tekton:
    enabled: false
...
```

In this case, tekton is not installed by default. If we want to install tekton altogether, we can overwrite the value `charts.tekton.enabled` as `true` before installation.

**Comment by JohnNiang** [comment]
@flamywhale Thanks for your patient explanation. That makes sense to me.

**Comment by flamywhale** [comment]
> Thanks for your contribution. But IMO, we don't have a good reason to maintain the Tekton helm chart. So, it's not a good idea to commit the source files of it into this repository. I have two suggestions here:
> 
> * commit and commit a specific release helm chart of Tekton
>   
>   * it should be a file likes `xxx.tgz`
> * create a PR against the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support)
>   
>   * we can merge the branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support) into master when it's ready

I am little confused about the second suggestion in which I am supposed to create a PR against the branch `tekton-support`.
Do I need to close this PR and create a new one for the branch `tekton-support`?

**Comment by JohnNiang** [comment]
hi @flamywhale , you can edit anything of this PR directly.

**Review by LinuxSuRen — COMMENTED** [review]
Everything is perfect. But it would be great if you can add a description about how (or where) do you get the chart zip file. For example, add a readme file under the directory: `charts/ks-devops/charts/`

**Comment by flamywhale** [comment]
> hi @flamywhale , you can edit anything of this PR directly.

Thanks!

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
> /label tide/merge-method-squash

It looks like the Prow has same problems.

**Pull request merged**
