### PR TITLE
Improve the notification of build result to git provider

### LINKED ISSUE #811: Improve the notification of build result to git provider
See also the following screenshot, it would be good to provide more information than the result.

image

The relevant source file is https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/controllers/gitrepository/pull_request_status_controller.go#L95

/good-first-issue

### PR DESCRIPTION
**Pull request by zhengzehong331**
### What type of PR is this?

/kind feature
### What this PR does / why we need it:
This PR Improve the notification of build result to git provider.  Contributors can view pipeline completion times and  status on the GitHub Checks.
### Which issue(s) this PR fixes:

Fixes #811

### Special notes for reviewers:

Please check the following list before waiting reviewers:

- [ ] Already committed the CRD files to [the Helm Chart](https://github.com/kubesphere-sigs/ks-devops-helm-chart/) if you created some new CRDs
- [ ] Already [added the permission](https://github.com/kubesphere/ks-installer/blob/9e063b085a0e43fdb3d0d9e3e7f4149146f14b9c/roles/ks-core/prepare/files/ks-init/role-templates.yaml) for the new API
- [ ] Already added the RBAC markers for the new controllers

### Does this PR introduce a user-facing change??

```release-note
None
```

### CODE REVIEW

**Review by yudong2015 — COMMENTED** [review]
@zhengzehong331 I can't found the code that setup the value of `[pipelinerun.Status.Description](https://github.com/kubesphere/ks-devops/pull/838/files#diff-722d341d55e177115f65c5997b24ba382992ae42a65a6a63db13e07c3f737612R107)`, so i think that the `[Description](https://github.com/kubesphere/ks-devops/pull/838/files#diff-e70818f68b8dfdc3fffd1b0836d3708d750d6c34a829788b38f6577ce7e5ae15R78)` of `PipelineRunStatus` is useless and unnecessary to add this field. The failed reason of pipelinerun could get from `PipelineRunStatus.Conditions` .

**Comment by zhengzehong331** [comment]
Thank you for your review @yudong2015，I have modified my code. I get the failed reason of pipelinerun from pipelinerun.Status.GetLatestCondition().Reason and I have deleted Description of PipelineRunStatus.

**Pull request merged**
