### PR TITLE
Reduce the complexity of Jenkins config controller

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Upstream https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/8

See [the design document](https://github.com/kubesphere/ks-devops/tree/master/controllers/jenkinsconfig) of this PR.

You can use the below image to test this PR:

`surenpi/devops-controller:dev--62e8d2c`

### CODE REVIEW

**Comment by JohnNiang** [comment]
When I changed some settings of `ks-jenkins.yaml` in `jenkins-casc-config` ConfigMap, but `jenkins.yaml` wasn't changed.

- Full log of `devops-ks-devops-controller`:

```go
W0824 05:44:50.112422       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0824 05:44:50.114176       1 server.go:144] setting up manager
I0824 05:44:50.148038       1 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"
I0824 05:44:50.151791       1 server.go:179] Starting cache resource from apiserver...
I0824 05:44:50.152008       1 server.go:182] Starting the controllers.
I0824 05:44:50.153318       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{}}}
I0824 05:44:50.153556       1 jenkinsconfig_controller.go:125] starting Jenkins config controller
I0824 05:44:50.153593       1 s2ibinary_controller.go:170] starting s2ibinary controller
I0824 05:44:50.153620       1 s2irun_controller.go:172] starting s2irun controller
I0824 05:44:50.153642       1 pipeline_controller.go:182] starting pipeline controller
I0824 05:44:50.153674       1 devopsproject_controller.go:187] starting devops project controller
I0824 05:44:50.153743       1 devopscredential_controller.go:192] starting devopscredential controller
I0824 05:44:50.154445       1 internal.go:391] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"
I0824 05:44:50.253870       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 05:44:50.253891       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 
I0824 05:44:50.253953       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "worker count"=1
I0824 05:46:07.207066       1 jenkinsconfig_controller.go:339] synced key: kubesphere-devops-system/jenkins-casc-config
I0824 05:46:07.207112       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 05:47:24.088029       1 jenkinsconfig_controller.go:339] synced key: kubesphere-devops-system/jenkins-casc-config
I0824 05:50:41.529710       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 05:51:57.855488       1 jenkinsconfig_controller.go:339] synced key: kubesphere-devops-system/jenkins-casc-config
```

**Comment by LinuxSuRen** [comment]
> When I changed some settings of ks-jenkins.yaml in jenkins-casc-config ConfigMap, but jenkins.yaml wasn't changed.

Acoording to [this design document](https://github.com/kubesphere/ks-devops/tree/master/controllers/jenkinsconfig#design), we don't change `jenkins.yaml` directly.

**Comment by JohnNiang** [comment]
While ` devops.kubesphere.io/jenkins-config-formula` was changed to `default` or `high`, some errors appeared:

```go
I0824 06:06:56.611871       1 jenkinsconfig_controller.go:219] Jenkins config formula name: low
E0824 06:06:56.641888       1 jenkinsconfig_controller.go:330] failed to update ConfigMap: kubesphere-devops-system/jenkins-casc-config
I0824 06:06:56.641917       1 jenkinsconfig_controller.go:331] synced key: kubesphere-devops-system/jenkins-casc-config
E0824 06:06:56.641958       1 jenkinsconfig_controller.go:167] error syncing 'kubesphere-devops-system/jenkins-casc-config': Operation cannot be fulfilled on configmaps "jenkins-casc-config": the object has been modified; please apply your changes to the latest version and try again, requeuing
I0824 06:06:56.642085       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 06:06:56.642139       1 jenkinsconfig_controller.go:219] Jenkins config formula name: low
I0824 06:08:13.196332       1 jenkinsconfig_controller.go:339] synced key: kubesphere-devops-system/jenkins-casc-config
I0824 06:08:13.196384       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 06:08:13.196417       1 jenkinsconfig_controller.go:219] Jenkins config formula name: high
E0824 06:08:13.254688       1 jenkinsconfig_controller.go:330] failed to update ConfigMap: kubesphere-devops-system/jenkins-casc-config
I0824 06:08:13.254722       1 jenkinsconfig_controller.go:331] synced key: kubesphere-devops-system/jenkins-casc-config
E0824 06:08:13.254764       1 jenkinsconfig_controller.go:167] error syncing 'kubesphere-devops-system/jenkins-casc-config': Operation cannot be fulfilled on configmaps "jenkins-casc-config": the object has been modified; please apply your changes to the latest version and try again, requeuing
I0824 06:08:13.254781       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config
I0824 06:08:13.254827       1 jenkinsconfig_controller.go:219] Jenkins config formula name: high
```

**Comment by JohnNiang** [comment]
It's recommended that we always use `/var/jenkins_home/casc_configs/jenkins.yaml`  as CASC source. Because the CASC source has been stuck in environment variable `CASC_JENKINS_CONFIG`. When Jenkins deployment is redeployed, the Jenkins will use `/var/jenkins_home/casc_configs/jenkins.yaml` even if we have set new source `/var/jenkins_home/casc_configs/ks-jenkins.yaml` before.

https://github.com/kubesphere/ks-devops/blob/c079dc39e4dbe2239c2a9fe115e58879a6593359/charts/ks-devops/charts/jenkins/values.yaml#L92-L94

**Before restarting Jenkins:**
image

**After restarting Jenkins:**
image

**Comment by LinuxSuRen** [comment]
We can take advantage of [this PR](https://github.com/jenkinsci/configuration-as-code-plugin/pull/1218) to improve the config missing issue.

See also Jenkins Configuration as Code [loads config files in order (in Chinese)](https://jenkins-zh.cn/tutorial/management/plugin/configuration-as-code/#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E6%B5%81%E7%A8%8B).

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , I found that the upstream PR got merged yesterday, how about this one?

**Comment by LinuxSuRen** [comment]
> Hi @LinuxSuRen , I found that the upstream PR got merged yesterday, how about this one?

I'm working on this. Thanks for the reminder.

**Comment by JohnNiang** [comment]
LGTM

**Pull request merged**
