### PR TITLE
Add lock for memory map cache, and add expire when get some key.

### PR DESCRIPTION
**Pull request by tmsi-io**

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
hi @tmsi-io , thanks for your contribution. I'm wondering if you could add some unit test cases for the new changes.

By the way, we have a SIG team that is responsible for this project. So, please cc this team if you'd like to ping someone. You can use it like this: `/cc @kubesphere/sig-devops `

**Comment by tmsi-io** [comment]
Ok, will try it later

**Comment by LinuxSuRen** [comment]
hi @tmsi-io ,Any updates about the unit tests? Do you need some help?

**Comment by LinuxSuRen** [comment]
Consider there is no response for a long time. I'm going to close this PR. @tmsi-io Please feel free to reopen it once you have free time on this.
/close

**Pull request closed without merging**
