### PR TITLE
docs: reformat code use go1.19

### PR DESCRIPTION
**Pull request by chengleqi**
### What type of PR is this?

/kind documentation

### What this PR does / why we need it:
These files changed when `make fmt` use go1.19.
[Go1.19 Release Note](https://tip.golang.org/doc/go1.19) Doc Comments Section.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:

Please check the following list before waiting reviewers:

- [ ] Already committed the CRD files to [the Helm Chart](https://github.com/kubesphere-sigs/ks-devops-helm-chart/) if you created some new CRDs
- [ ] Already [added the permission](https://github.com/kubesphere/ks-installer/blob/9e063b085a0e43fdb3d0d9e3e7f4149146f14b9c/roles/ks-core/prepare/files/ks-init/role-templates.yaml) for the new API
- [ ] Already added the RBAC markers for the new controllers

### Does this PR introduce a user-facing change??
None

```release-note
```

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
hi @chengleqi , thanks for your great effort on this. But why we should upgrade Go from 1.16 to 1.19?

https://github.com/kubesphere/ks-devops/blob/4c6a153555b85a321fad7fca2e2aaf681f858dcb/go.mod#L3

**Comment by chengleqi** [comment]
> hi @chengleqi , thanks for your great effort on this. But why we should upgrade Go from 1.16 to 1.19?
> 
> https://github.com/kubesphere/ks-devops/blob/4c6a153555b85a321fad7fca2e2aaf681f858dcb/go.mod#L3

Oh, my local env is go1.19. Everytime I run `make` these files were changed and I have to restore these files.
I should setup go1.16 in my local env. XD

**Comment by LinuxSuRen** [comment]
> my local env is go1.19

Actually, everyone's dev environment might have different Go versions. I prefer to install Go 1.16 before we have a solid reason to upgrade the version. By the way, many IDE is able to set a specific version. For example, Goland.

**Comment by chengleqi** [comment]
Really thanks for your advice.

**Pull request closed without merging**
