### PR TITLE
fix: ParameterReference apiGroup empty

### PR DESCRIPTION
**Pull request by lxm**
/kind bug

pipeline save will get a error when apiGroup is empty.

https://github.com/kubernetes/kubernetes/issues/79354

Although the comment says it's optional, we'll still get an error if we pass null because there's no omitempty 

### Does this PR introduce a user-facing change??

```release-note
None
```

### CODE REVIEW

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
hi @lxm , just a friendly tip. The CI process is failed.

**Comment by lxm** [comment]
> CI

right, but I think the CI failure has nothing to do with this PR. We need another PR to fix the security issue.

**Comment by LinuxSuRen** [comment]
> I think the CI failure has nothing to do with this PR. We need another PR to fix the security issue.

Fair enough. Let's just hold this PR until the blocked issues are fixed.
/hold

**Comment by LinuxSuRen** [comment]
Now @lxm you can rebase the current branch to upstream/master. I belive the CI will pass.

**Pull request merged**
