### PR TITLE
Provide Kubernetes matrix E2E testing

### LINKED ISSUE #347: Provide Kubernetes matrix to run E2E testing.
KubeSphere 3.2.0 announced Supported Kubernetes versions are v1.19.x, v1.20.x, v1.21.x or v1.22.x (experimental). So we have to target those versions to provide corresponding E2E testing.

Please see also https://kubesphere.io/docs/installing-on-linux/introduction/kubekey/#Support%20Matrix.

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose?

Provide Kubernetes matrix E2E testing.

### Why we need it?

Please see #347.

### Which issue dose this PR fix?

Fix #347

### Special notes for reviewer

Upstream PR: #343 

/kind feature

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
Everything is great. But I'm thinking about if you could provide some documents about your changes. For instance:

* the structure of the e2e tests
* when people should take care of the e2e? Do they need to add e2e test cases for any new features?
* how to add a new Kubernetes version tests
* others

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , thanks for your reminder. I have a plan to provide a E2E testing documentation and will put your suggestion into #350.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
