### PR TITLE
remove unused method parameters

### PR DESCRIPTION
**Pull request by nuclearwu**
### What type of PR is this?
/kind cleanup

### What this PR does / why we need it:
remove unused method parameters

### Which issue(s) this PR fixes:
Fixes #

### Special notes for reviewers:
/cc @kubesphere/sig-devops 

Please check the following list before waiting reviewers:

- [ ] Already committed the CRD files to [the Helm Chart](https://github.com/kubesphere-sigs/ks-devops-helm-chart/) if you created some new CRDs
- [ ] Already [added the permission](https://github.com/kubesphere/ks-installer/blob/9e063b085a0e43fdb3d0d9e3e7f4149146f14b9c/roles/ks-core/prepare/files/ks-init/role-templates.yaml) for the new API
- [ ] Already added the RBAC markers for the new controllers

### Does this PR introduce a user-facing change??
None

```release-note
None
```

### CODE REVIEW

**Review by mangoGoForward — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
hi @nuclearwu , so glad to see you here. I have made your first contribution.

Before getting it merged, there is one thing that you might need to do. IMO, this is a minor change, we might don't need to put it in the changelog. So, I'd like to suggest making the following changes (see the screenshot):

image

**Comment by nuclearwu** [comment]
> 

done

**Pull request merged**
