### PR TITLE
Fix error handle jclient.NewJenkinsClient()

### PR DESCRIPTION
**Pull request by ciiiii**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:
If jenkinsCore.GetCrumb() failed, error won't be return and JenkinsClient will be nil. 
This makes program panic and no error message showed up.
https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/pkg/client/devops/jclient/jenkins.go#L30-L40
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:

```release-note
None
```

### Does this PR introduce a user-facing change??

```release-note

```

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
hi @ciiiii thanks for helping to fix it.

/lgtm

**Comment by LinuxSuRen** [comment]
> /assign @LinuxSuRen

We have SIG which is responsible for the DevOps area. So you can cc the whole team next time.

/cc @kubesphere/sig-devops

**Review by JohnNiang — APPROVED** [review]
Thank you for your contribution! I encountered this problem yesterday as well.

/lgtm
/approve

**Comment by LinuxSuRen** [comment]
/approve

> We have a WeChat group. Please add me with `linuxsuren` if you want to join it.

**Pull request merged**
