### PR TITLE
Refine Swagger config to access Swagger UI in development environment

### PR DESCRIPTION
**Pull request by JohnNiang**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:

According to https://github.com/emicklei/go-restful-swagger12#how-to-use-swagger-ui-with-go-restful, I refined the swagger config when registering Swagger service.

```go
config := swagger.Config{
	WebServices:    restful.RegisteredWebServices(),
	ApiPath:        "/apidocs.json",
	SwaggerPath:     "/apidocs/",
	SwaggerFilePath: "/Users/emicklei/Projects/swagger-ui/dist"}
swagger.InstallSwaggerService(config)		
```

In `config/apiserver/Dockerfile`, the swagger config is suitable for that, but when we develop in local environment we cannot access the Swagger UI  properly via <http://localhost:9090/apidocs/?url=http://localhost:9090/apidocs.json>.

In this PR, I correct the SwaggerFilePath config and refine `config/apiserver/Dockerfile`. This fix has no impact on how APIServer that are already deployed can access API documentation.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:

Docker image for test:

```
johnniang/devops-apiserver:dev-v3.2.1-cd84037
```

### Does this PR introduce a user-facing change??

```release-note
None
```

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
I'm wondering if you missed the makefile.

**Comment by JohnNiang** [comment]
> I'm wondering if you missed the makefile.

Hi @LinuxSuRen , thanks for your reminder! 

The `swagger-ui` target in Makefile is ok I think, please see:

https://github.com/kubesphere/ks-devops/blob/e08b477fc8fffab600801a82a3adbf279ff565a0/Makefile#L119-L120

What we want is just to clone swagger into `bin/swagger-ui` directory. Is there anything I missed? Please feel free to correct me.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
